.TH UPDATE-DISTCC-SYMLINKS 8 "2011-11-03"
.SH NAME
update-distcc-symlinks \- update symlinks in /usr/lib/distcc
.SH SYNOPSIS
.B update-distcc-symlinks
.SH DESCRIPTION
\fBupdate-distcc-symlinks\fR creates and removes symlinks in
\fI/usr/lib/distcc\fR. See the \fBdistcc\fR man page for more information.
.P
It is normally not necessary to run \fBupdate-distcc-symlinks\fR by hand as
this is done automatically when compiler packages are removed or
installed.
.SH SEE ALSO
.BR distcc (1)
.SH AUTHOR
This manual page was written by Joel Rosdahl <joel@debian.org> for the
Debian GNU/Linux system.
